[package]
name = "readall"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["wayland"]
wayland = ["readall-platform/wayland"]

[dependencies]
readall-epub.workspace = true
readall-font.workspace = true
readall-core.workspace = true
readall-render.workspace = true
readall-platform.workspace = true

[lints]
workspace = true
